### ISSUE TITLE
Feat: Manual testing of Sign up and Sign in feature

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/FitMate#10]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**
Download the apk[[release version](https://github.com/Code-Sauce-Official/FitMate/releases/tag/1.0)] and test all different scenarios for sign up and sign in.

An md file with all the test scenarios you covered. Positive and negative test cases as expected. Each test scenario should be documented as below:

```
* _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:

* _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ...  
```
**Additional context**
Add your markdown(md) file in [Testing folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing)
`If you see issues or unexpected behavior during testing feel free to open an issue`

**Comment by remote007** [comment]
I'd like to work on this issue under LGMSOC'21.

**Comment by SHITIZ-AGGARWAL** [comment]
@PadminiRai You can take up at max 2 issues at a time.
If you complete your previous issue and no one is assigned to this issue then you can be assigned here.

**Comment by KishkinJ10** [comment]
can I work on this I am LGM-SOC participant

**Comment by SHITIZ-AGGARWAL** [comment]
@KishkinJ10  Sure go ahead

**Comment by KishkinJ10** [comment]
@Sakalya100  I am already working on this issue .

**Comment by Sakalya100** [comment]
Really sorry @KishkinJ10 I mentioned the wrong issue number in my pull request. Apology from my side

**Comment by KishkinJ10** [comment]
Ok @Sakalya100 sir no problem .
