### ISSUE TITLE
Feat: Research on GitHub workflows

### ISSUE THREAD

**Issue by nidhisingh-1** [Code-Sauce-Official/FitMate#13]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**
Do research on GitHub actions that can be implemented in this project and compile your research in a markdown file (.md).

**Additional context**
[For Reference](https://docs.github.com/en/actions)
Please note that you have to add the file in [research folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Research).

**Comment by remote007** [comment]
I'd like to work on this issue under label LGMSOC'21.

**Comment by nidhisingh-1** [comment]
Okay, assigning this issue to you.

**Comment by remote007** [comment]
@nidhisingh-1 could you please assign this issue under the **label :  LGMSOC'21**

**Comment by remote007** [comment]
@nidhisingh-1 , can formatting techniques like bold font style , bullet list be used for visual clarity and better understanding .

**Comment by remote007** [comment]
![ss1](https://user-images.githubusercontent.com/59466080/121831820-1c0b9e80-cce6-11eb-897d-4e2e5f40bc6b.JPG)
@nidhisingh-1 
Also there are **8880+ actions** , so how'd you like me to boil down my research ?

**Comment by SHITIZ-AGGARWAL** [comment]
@PadminiRai Look for actions that can help in maintaining the android project
[This](https://medium.com/google-developer-experts/github-actions-for-android-developers-6b54c8a32f55) might be helpful

**Comment by remote007** [comment]
@SHITIZ-AGGARWAL Thanks for your insight and reference. I'm on it.

**Comment by PadminiRai** [comment]
@nidhisingh-1 Thanks for the insights . I've created  the PR : https://github.com/Code-Sauce-Official/FitMate/pull/57

**Comment by remote007** [comment]
@nidhisingh-1  and @SHITIZ-AGGARWAL   Thanks for the insights . I've created  the PR : https://github.com/Code-Sauce-Official/FitMate/pull/59
