### ISSUE TITLE
Feat: Redesign FitMate logo

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/FitMate#15]
**What is your issue related to ?**

- [ ] Code
- [x] Designing
- [ ] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Make a new logo for FitMate. The logo should be relevant to our application.

**Additional context**
Check out [design](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Designs/FigmaDesign/Design.md) for reference

**Comment by Ayushi7456** [comment]
I would like to work on this. Assign me.

**Comment by SHITIZ-AGGARWAL** [comment]
Sure go ahead

**Comment by SHITIZ-AGGARWAL** [comment]
@Ayushi7456 Before making the PR , share your design in the comments

**Comment by Ayushi7456** [comment]
Ok sure.

**Comment by Astitva7717** [comment]
May I try this as well under LGMSOC21 ??

**Comment by SHITIZ-AGGARWAL** [comment]
@Astitva7717  Sure go ahead
Before making the PR , share your design in the comments

**Comment by sowmiyeh** [comment]
I would like to work on this. Please assign me this

**Comment by sowmiyeh** [comment]
**Fitmate Logo Redesign**

### Figma Link : [https://www.figma.com/file/ZcaLJikRsoRvH9wzRH1yNK/Fitmate-logo-redesign?node-id=0%3A1](url)

**Comment by SHITIZ-AGGARWAL** [comment]
@Ayushi7456 @Astitva7717 Update

**Comment by SHITIZ-AGGARWAL** [comment]
@sowmiya-venkatesan 
Add a .svg file of your logo in Logo folder [Here](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Designs/Contributions/Logo)
And add your name in [Readme](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Designs/Contributions/Logo#contributors) with this template

**and make sure to create a branch first then work on it and then create pull request from that branch**

```
Name : your_name
Logo Link : [ figma link/ .svg file link / drive link / public link ] any one will work 

```

**Comment by Ayushi7456** [comment]
> @Ayushi7456 @Astitva7717 Update 
I haven't worked yet as i am working on a coding project. You can assign to others.
