### ISSUE TITLE
Feat: Look for an api from where we can fetch regularly updated Fitness blogs for the Insights screen

### ISSUE THREAD

**Issue by Acash512** [Code-Sauce-Official/FitMate#17]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**

The insights screen has to be implemented for which we are supposed to show regularly updated blogs for each category like Gym, Mind, Sports, Diet etc. We need an api for the same whose endpoints are freely available which can be used for quering in our app using Retrofit library.

**Additional context**

| <img src="https://user-images.githubusercontent.com/53511962/121026227-8fcc1980-c7c3-11eb-87e7-41ca1a43419c.png" width="250"/> | <img src="https://user-images.githubusercontent.com/53511962/121026285-9b1f4500-c7c3-11eb-9805-8a1c4161c6d4.png" width="250"/> | <img src="https://user-images.githubusercontent.com/53511962/121026310-9fe3f900-c7c3-11eb-9948-5effca477076.png" width="250"/> |
|---|---|---|

| <img width="250" src="https://user-images.githubusercontent.com/53511962/121026328-a5414380-c7c3-11eb-8987-2006e0f84029.png"> | <img width="250" src="https://user-images.githubusercontent.com/53511962/121026349-aa05f780-c7c3-11eb-9b8e-be0c3fa806a2.png"> |
|---|---|

Add your markdown(md) file in [Research folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Research)

**Comment by Sakalya100** [comment]
@SHITIZ-AGGARWAL I would like to work upon this issue. Kindly assign me this

**Comment by SHITIZ-AGGARWAL** [comment]
@Sakalya100 Go ahead

**Comment by SHITIZ-AGGARWAL** [comment]
Before making a pr , comment your findings

**Comment by Sakalya100** [comment]
Ok sure @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@Sakalya100 update

**Comment by sejalvasan** [comment]
Can I work on this issue under LGM SOC?

**Comment by Sakalya100** [comment]
@SHITIZ-AGGARWAL Having my exams so will start working just after some days
