### ISSUE TITLE
Feat: Update Readme.md

### ISSUE THREAD

**Issue by nidhisingh-1** [Code-Sauce-Official/FitMate#18]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Check for grammatical errors, add relevant badges, stats, tech stack logos, etc.

**Additional context**
[For reference](https://towardsdatascience.com/build-a-stunning-readme-for-your-github-profile-9b80434fe5d7)

**Comment by yjaiswal05** [comment]
I want to work on this issue

**Comment by nidhisingh-1** [comment]
Okay. Assigning this issue to you @yjaiswal05

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by nidhisingh-1** [comment]
@jayant766, we have already assigned @yjaiswal05 as of now to work on this issue. You may find other issues to work on :)
