### ISSUE TITLE
Bug: For people who don't have a dp, sometimes someone else's dp is displayed in inbox

### ISSUE THREAD

**Issue by Acash512** [Code-Sauce-Official/FitMate#19]
## Expected Behavior
If there is no dp for a partner in a user's inbox, default avatar should be displayed 

## Actual Behavior
Sometimes some other user's dp from the list is displayed instead of default avatar

## Steps to Reproduce the Problem

1. Go to My Partners
2. Make sure there is a partner having no dp, and a partner having a dp
3. Click on one of them which will take you to the respective chat
4. Press back, now when when you are redirected to the My Partners screen you will see the problem

## Solution to the problem

The reason for the described behaviour is that Recycler View (which has been used for displaying Partners) reuses previous views so if we don't set a default avatar when download url for dp is blank, it retains the previous image set in the image view thereby causing the error.

In bindViewHolder() function of InboxViewHolder when download url for dp (inbox.image) is blank, load default avatar in userImgView using Glide library.

## Specifications

- Device - Redmi 6A
- Android version - 9.0

## Screenshots

| Expected | Actual |
|---|---|
| <img src ="https://user-images.githubusercontent.com/53511962/121034296-8abe9880-c7ca-11eb-9667-3bb4fc0084a7.jpeg" width =250/> | <img src ="https://user-images.githubusercontent.com/53511962/121034313-8d20f280-c7ca-11eb-9b6d-0f0d2054b7e9.jpeg" width=250/> |

**Comment by toth2000** [comment]
Can I work on this issue?. (LGM-SOC'21)

**Comment by Acash512** [comment]
> Can I work on this issue?. (LGM-SOC'21)

Yeah sure
