### ISSUE TITLE
Bug: Order partners in inbox on the basis of time instead of key

### ISSUE THREAD

**Issue by Acash512** [Code-Sauce-Official/FitMate#20]
## Expected Behavior

The partners in My Partners fragment must be ordered in descending order of the time last message was sent or received for that person.

## Actual Behavior

The partners are ordered in ascending order of their auth uid. 

## Screenshots

<img src ="https://user-images.githubusercontent.com/53511962/121037793-61533c00-c7cd-11eb-953e-9c5761391c17.jpeg" width = 250/>

As evident from the screenshot a chat for which last msg was sent on 31st May is shown after msgs sent on 30th May

## Specifications

- Device - Redmi 6A
- Android version - 9.0

**Comment by amksde** [comment]
Do you have some database structure or design which we can refer to? Only one line is needed to reorder the query coming from Firestore, but for that `orderBy` clause one would need the database design so that we can put the relevant argument.

**Comment by Acash512** [comment]
> Do you have some database structure or design which we can refer to? Only one line is needed to reorder the query coming from Firestore, but for that `orderBy` clause one would need the database design so that we can put the relevant argument.

The problem is the partners for a user's inbox are stored in real time database and not firestore, that's where the time for last msg sent is stored as well, henceforth they are ordered on the basis of key by default

**Comment by amksde** [comment]
Still, you can [order the query](https://firebase.google.com/docs/database/web/lists-of-data#sort_data) using the clauses given in the link. If you'd want someone from outside your organization to fix the bugs, then you'd have to provide the database details/structure too. It'd be helpful for contributors if you could provide a diagram sort of thing for the database structure in the documentation perhaps.

**Comment by Acash512** [comment]
Ya I have that in mind, will be sharing that soon

**Comment by Rohit-2602** [comment]
Does this work orderByChild("time")??

**Comment by Acash512** [comment]
I tried that actually but it didn't help

**Comment by Rohit-2602** [comment]
@Acash512 Can we just store timeInstanse (System.currentTimeMillis)?? and use OrderByChild("time").
and in recyclerview we again convert millis to data time format

**Comment by Acash512** [comment]
It might work, you may try it out, assigning this issue to you

**Comment by Acash512** [comment]
Make sure you make changes accordingly, wherever necessary, also attach appropriate screenshots in the pr.

**Comment by Rohit-2602** [comment]
@Acash512 I don't have any Partners 🥲 right now, so I guess I can't attach SS.

**Comment by Acash512** [comment]
You can sign out and use another email of yours for testing purposes

**Comment by Acash512** [comment]
<img src ="https://user-images.githubusercontent.com/53511962/121707420-28c8a080-caf4-11eb-847d-e6702bc948a1.png" width =1000/>

Have a look at the above screenshot, I guess the time field within time is System.currentTimeMillis() only, see if you can order wrt that field, that would be much easier otherwise try out what you mentioned above.

**Comment by Rohit-2602** [comment]
@Acash512 PR is up.
