### ISSUE TITLE
Feat: Customise Readme with screenshots

### ISSUE THREAD

**Issue by KhushiSharma22** [Code-Sauce-Official/FitMate#22]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [ ] Documentation
- [ ] Testing/Research
- [-] Others[please specify]: Making the project better and stand out amongst the audience.

**Description**
Customising the Readme file with some screenshots of the key features of the app would make it really easy for anyone navigating through the project's GitHub to understand the project. 

You can add some screenshots and that would your project stand out.

**Comment by nidhisingh-1** [comment]
@KhushiSharma22 , this issue[#18] has already been created. No need to make a separate issue.

**Comment by KhushiSharma22** [comment]
I think that issue was much more related to different stuff, just wanted to point out this particular thing. 

Closing this one.

**Comment by SHITIZ-AGGARWAL** [comment]
@KhushiSharma22 Got your point ,we also have screenshots of the key features in designs 
[here](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Designs#readme)
If you are interested on working you can work on #18 and also add a new section for screenshots there
