### ISSUE TITLE
Feat: Remove partners array field from User Model

### ISSUE THREAD

**Issue by yatharthmago01** [Code-Sauce-Official/FitMate#27]
**What is your issue related to ?**

- [x] Code
- [ ] Designing
- [ ] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
The partners of a user are stored in Inbox in Realtime Database. So there's no need for the same partners array to be stored in the UserModel class, and therefore Firestore. In short, this field is useless.  

**Describe the solution you'd like**
Remove partners array field from UserModel

**Comment by Rohit-2602** [comment]
Can I work on this issue?

**Comment by yatharthmago01** [comment]
Yeah sure go ahead!

**Comment by Rohit-2602** [comment]
@yatharthmago01 Can you review this PR.
