### ISSUE TITLE
Feat: Design Profile screen

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/FitMate#28]
### What is your issue related to ?

- [ ] Code
- [x] Designing
- [ ] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

### Description

Design a Profile Screen for FitMate where the user will be able to see
- DP
- NAME
- GENDER
- DOB
- STATE (Drop Down Menu)
- BADGES EARNED 

#### For reference you can visit [Design](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Designs/FigmaDesign/Design.md)
<img src = "https://user-images.githubusercontent.com/53532851/121522856-2e01ee80-ca13-11eb-849f-b8e9426dedbc.png" width="300px" >

### Additional context

[FIGMA DESIGN LINK](https://www.figma.com/file/sslRspiHqmjeldYpMr6OdJ/FitMate-Dark-Theme?node-id=0%3A1)

**Comment by AkshayTati** [comment]
I'd like to work on this issue.
(LGM SOC)

**Comment by SHITIZ-AGGARWAL** [comment]
Sure Go ahead

**Comment by sowmiyeh** [comment]
I would like to work on this. Please assign me this

**Comment by Viditjain04** [comment]
I'd like to work on this issue. please assign me this (LGM SOC)

**Comment by SHITIZ-AGGARWAL** [comment]
@Viditjain04 Sure go ahead

**Comment by sowmiyeh** [comment]
### Fitmate : Display Profile Screen
Figma Link : https://www.figma.com/file/JsFndwt7dCGtKnAQLe1QGj/Fitmate-profile-screen?node-id=4%3A348
Prototype : https://www.figma.com/proto/JsFndwt7dCGtKnAQLe1QGj/Fitmate-profile-screen?node-id=33%3A195&scaling=min-zoom&page-id=4%3A348
Demo Link : https://photos.app.goo.gl/D9nb83RpZtptoqLfA

**Comment by SHITIZ-AGGARWAL** [comment]
@sowmiya-venkatesan Good Work
Create a pull request 
Make a new folder in Contributions folder   [here](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Designs/Contributions) and add your designs in it [.svg]
