### ISSUE TITLE
Image for readme

### ISSUE THREAD

**Issue by yjaiswal05** [Code-Sauce-Official/FitMate#32]
I'm just opening this issue for the link and will delete later on
![UIUX-mockup_compress99](https://user-images.githubusercontent.com/71898427/121775809-5cb0ce00-cba7-11eb-8bcb-1cea314a0b37.jpg)

**Comment by SHITIZ-AGGARWAL** [comment]
@yjaiswal05 You can get link from uploading in comments also

**Comment by SHITIZ-AGGARWAL** [comment]
therefore closing the issue

**Comment by SHITIZ-AGGARWAL** [comment]
you can upload here if you want more urls

**Comment by yjaiswal05** [comment]
Sure sure
