### ISSUE TITLE
Bug: Update Accept Request

### ISSUE THREAD

**Issue by Rohit-2602** [Code-Sauce-Official/FitMate#33]
## Expected Behavior

When we accept a request, it shouldn't navigate back to the previous activity.

## Actual Behavior

It navigates.

## Steps to Reproduce the Problem

1. Remove onBackPressed() call.

## Specifications

Describe any relevant information related to issue

- Your phone model
- Android version

**Screenshots**

**Additional context**

**Comment by Rohit-2602** [comment]
@Acash512 Can you assign this to me :eyes:.

**Comment by Acash512** [comment]
Yeah sure🙂
