### ISSUE TITLE
Feat: Add UI button designs

### ISSUE THREAD

**Issue by ayushsoni1010** [Code-Sauce-Official/FitMate#37]
**What is your issue related to ?**

- [ ] Code
- [x] Designing
- [ ] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Write about the problem or idea you want to refer to in this issue.
-- I want to add UI buttons so when a user Tap on it. It gives such beautiful animations/effects like Hover/Tap :) 

**Describe the solution you'd like**
A description of the solution you would suggest if any.
-- Yeah, if we add this feature then a user feels so soothing dealing with the buttons as he/she can stress out :)) . 
They will start it, again and again, to tap on it and started loving buttons in the app 
People will get attraction here, as this a fitness app, sometimes users get stressed, so by this also they can relief by the soothing UI buttons :)
By adding this feature, more users will get attracted towards *FitMate* android application

**Additional context**
-- I will provide it soon :)
Kindly assign me this issue under LGMSOC'21
Thanks :)

**Comment by SHITIZ-AGGARWAL** [comment]
@ayushsoni1010  Before making the PR , provide ss in comments

**Comment by ayushsoni1010** [comment]
I have added two samples with app color code 

https://xd.adobe.com/view/60e9c8b7-ecef-4f04-b22c-948b239ef543-35ba/

Hope you like it :)

**Comment by SHITIZ-AGGARWAL** [comment]
@ayushsoni1010 Change the colour scheme according to FitMate colour scheme.  Also you need to make these effects on tap bcz in a mobile application hover is not applicable

**Comment by ayushsoni1010** [comment]
Sure, I will look at this :)

Later, I will reshare the link of Adobe XD once done

**Comment by ayushsoni1010** [comment]
I have made changes to the `Tap` instead of hover.
Please specify which UI you like the most so I can work with that UI button properly
