### ISSUE TITLE
Bug: Update Partner Request

### ISSUE THREAD

**Issue by Rohit-2602** [Code-Sauce-Official/FitMate#38]
## Expected Behavior

If a User is Partner with another user. Then, both of them shouldn't be able to send requests again. And if the request is already sent to the user, then a Toast message appears "Request Already Sent".

## Actual Behavior

If users are partners with each other, then they can send requests again and again.

## Steps to Reproduce the Problem

1. Check if the user (sending a request to) is present in Inbox.
2. If present then shows Toast Message, else send the request.

## Specifications

Describe any relevant information related to issue

- Your phone model
- Android version

**Screenshots**

**Additional context**

**Comment by Rohit-2602** [comment]
@Acash512 @SHITIZ-AGGARWAL Can you review and assign this is issue to me.

**Comment by Acash512** [comment]
Ya you can work on this
