### ISSUE TITLE
Feat: Format tests

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/FitMate#54]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [x] Format

**Description**
Format sign up/sign in test document
Change the format of all tests similar to test 1

**Describe the solution you'd like**
|       After CHANGING      |  ORIGINAL |
:-------------------------:|:-------------------------:
|<img src = "https://user-images.githubusercontent.com/53532851/122553430-48f8e200-d055-11eb-9408-6365c295cde7.png" width="400px">|<img src = "https://user-images.githubusercontent.com/53532851/122553460-52824a00-d055-11eb-9bd8-19d4c8f15542.png" width="400px">|

|       TARGET    |  ORIGINAL |
:-------------------------:|:-------------------------:
|<img src = "https://user-images.githubusercontent.com/53532851/122554340-78f4b500-d056-11eb-9aaa-54541773d7e5.png" >|<img src = "https://user-images.githubusercontent.com/53532851/122554354-7eea9600-d056-11eb-9854-615defb73b6b.png" >|

### You have to format every test like this from test-2 to test-15
[File](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/Testing/SignUpTesting.md)

**Comment by subhasmitapradhan** [comment]
I would like to work on this issue.

**Comment by SHITIZ-AGGARWAL** [comment]
@subhasmitapradhan Sure go ahead

**Comment by sreenathpranav** [comment]
I would like to work on some documentation is there any available?
