### ISSUE TITLE
Feat: add some badges to README.md file

### ISSUE THREAD

**Issue by Umesh-01** [Code-Sauce-Official/FitMate#56]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
add badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/122651603-8d6ca680-d157-11eb-8ccb-f0c3a5d539c0.png)

**Describe the solution you'd like**
I will add some badges and also will add links related to them to the top so that the README.md file will look more interactive and awesome.

**Work under/as**
- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@Acash512 @SHITIZ-AGGARWAL should I make these changes??

**Comment by SHITIZ-AGGARWAL** [comment]
@Umesh-01 All the necessary badges have been added. Since navigation through code, PR and issues can be easily done from the top there is no need for such badges. If you have any other idea feel free to tell in comments
