### ISSUE TITLE
Update Contribution Guildelines File

### ISSUE THREAD

**Issue by Shaishav0507** [Code-Sauce-Official/FitMate#58]
Hey @SHITIZ-AGGARWAL @Acash512 
I would like to add contribution guidelines file as it contains no commands to help the user.
I will add some commands helpful for the project.
Please assign it to me.
Thanks

**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [ ] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)

**Describe the solution you'd like**
A description of the solution you would suggest if any. (Any suggestions for solving the issue)

**Additional context**

**Comment by SHITIZ-AGGARWAL** [comment]
@Shaishav0507 We already have [contributing guidelines](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/CONTRIBUTING.md) and [how to start](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/HowToStart.md)
