### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [Code-Sauce-Official/FitMate#61]
I would like to add step be step procedure for the Beginners in open-source. Please assign this to me

**Comment by nidhisingh-1** [comment]
Hi, @swathi-469 thanks for opening this issue but I collect that the guidelines for the same have already been mentioned in the readme and contributing guidelines as well. I am closing this issue as of now, you can look up other issues to work on that match your expertise or create another suitable one, we will be happy to help you out.
