### ISSUE TITLE
Feat: Write code of conduct

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/FitMate#9]
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Write code of conduct for the repository

**Describe the solution you'd like**
You can read Github docs for more information. 
[[Reference](https://github.com/anitab-org/mentorship-android/blob/develop/docs/CODE_OF_CONDUCT.md#code-of-conduct)]

**Additional context**
A file for the same has already been created, you have to add the content in same.[[Here](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/CodeOfConduct.md)]

**Comment by Pratibha-Rawat** [comment]
I would like to work on this issue. Kindly assign me this issue.

**Comment by yatharthmago01** [comment]
Yeah sure go ahead!
